#!/usr/bin/env python
# coding: utf-8

"""
Train personalized neural-network models of HCP resting-state fMRI.

This script uses the arrays generated by:

    scripts/01_preprocess_rest.py

Expected inputs
---------------
For each participant:

    results/processed/<subject>_inputs.npy
    results/processed/<subject>_targets.npy

Saved outputs
-------------
For each participant:

    results/ANN_model/<subject>_MLP.pt
    results/ANN_model/<subject>_MLP_results.npy

The participant cohort and its order are defined by:

    data/Task/language_subjects_paper100.txt
"""

from pathlib import Path
import argparse
import gc
import os
import sys

import numpy as np
import torch


# Occasionally needed to avoid local MKL/OpenMP conflicts.
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")


# =============================================================================
# Repository paths
# =============================================================================

script_dir = Path(__file__).resolve().parent
hcp_dir = script_dir.parent
repo_dir = hcp_dir.parent.parent

preproc_dir = hcp_dir / "results" / "processed"
save_dir = hcp_dir / "results" / "ANN_model"
subject_list_file = (
    hcp_dir
    / "data"
    / "Task"
    / "language_subjects_paper100.txt"
)

if str(hcp_dir) not in sys.path:
    sys.path.insert(0, str(hcp_dir))

from src import NPI


# =============================================================================
# Model parameters used in the paper
# =============================================================================

METHOD = "MLP"
ROI_NUM = 450
USING_STEPS = 3

BATCH_SIZE = 64
TRAIN_SET_PROPORTION = 0.90
NUM_EPOCHS = 50
LEARNING_RATE = 5e-4
L2_REG = 5e-5


# =============================================================================
# Utilities
# =============================================================================

def load_paper_subject_ids() -> list[str]:
    """
    Load the 100 participant IDs used in the paper.

    The preprocessing files normally retain the HDF5 prefix "id_", whereas
    the participant-list file contains only the numeric HCP identifier.
    """
    if not subject_list_file.is_file():
        raise FileNotFoundError(
            f"Participant list not found: {subject_list_file}"
        )

    with subject_list_file.open("r", encoding="utf-8") as file:
        numeric_ids = [
            line.strip()
            for line in file
            if line.strip()
        ]

    if len(numeric_ids) != 100:
        raise ValueError(
            "Expected 100 participant IDs, but found "
            f"{len(numeric_ids)} in {subject_list_file}."
        )

    if len(set(numeric_ids)) != len(numeric_ids):
        raise ValueError(
            "The participant list contains duplicate IDs."
        )

    return [f"id_{subject_id}" for subject_id in numeric_ids]


def validate_processed_files(subject_ids: list[str]) -> None:
    """Check that model inputs and targets exist for every participant."""
    if not preproc_dir.is_dir():
        raise FileNotFoundError(
            "Processed-data directory not found: "
            f"{preproc_dir}\n"
            "Run scripts/01_preprocess_rest.py first."
        )

    missing_files = []

    for subject_id in subject_ids:
        input_path = preproc_dir / f"{subject_id}_inputs.npy"
        target_path = preproc_dir / f"{subject_id}_targets.npy"

        if not input_path.is_file():
            missing_files.append(str(input_path))

        if not target_path.is_file():
            missing_files.append(str(target_path))

    if missing_files:
        preview = "\n".join(missing_files[:20])

        if len(missing_files) > 20:
            preview += (
                f"\n... and {len(missing_files) - 20} more missing files."
            )

        raise FileNotFoundError(
            "Some required processed files are missing:\n"
            + preview
        )


def train_subject(
    subject_id: str,
    overwrite: bool = False,
) -> bool:
    """
    Train and save one participant-specific model.

    Returns
    -------
    bool
        True when a model was trained and saved, and False when an existing
        model was skipped.
    """
    model_path = save_dir / f"{subject_id}_{METHOD}.pt"
    results_path = save_dir / f"{subject_id}_{METHOD}_results.npy"

    if model_path.exists() and not overwrite:
        print(
            f"Skipping {subject_id}: model already exists at "
            f"{model_path}"
        )
        return False

    input_path = preproc_dir / f"{subject_id}_inputs.npy"
    target_path = preproc_dir / f"{subject_id}_targets.npy"

    print(f"\nTraining participant {subject_id} with {METHOD}")

    inputs = np.load(input_path)
    targets = np.load(target_path)

    if inputs.ndim != 2:
        raise ValueError(
            f"Expected 2D inputs for {subject_id}, got {inputs.shape}."
        )

    if targets.ndim != 2:
        raise ValueError(
            f"Expected 2D targets for {subject_id}, got {targets.shape}."
        )

    expected_input_width = ROI_NUM * USING_STEPS

    if inputs.shape[1] != expected_input_width:
        raise ValueError(
            f"Unexpected input width for {subject_id}: "
            f"{inputs.shape[1]}; expected {expected_input_width}."
        )

    if targets.shape[1] != ROI_NUM:
        raise ValueError(
            f"Unexpected target width for {subject_id}: "
            f"{targets.shape[1]}; expected {ROI_NUM}."
        )

    if inputs.shape[0] != targets.shape[0]:
        raise ValueError(
            f"Inputs and targets contain different numbers of samples for "
            f"{subject_id}: {inputs.shape[0]} and {targets.shape[0]}."
        )

    model = NPI.build_model(
        METHOD,
        ROI_NUM,
        USING_STEPS,
    )

    model, train_loss, test_loss = NPI.train_NN(
        model,
        inputs,
        targets,
        batch_size=BATCH_SIZE,
        train_set_proportion=TRAIN_SET_PROPORTION,
        num_epochs=NUM_EPOCHS,
        lr=LEARNING_RATE,
        l2=L2_REG,
    )

    torch.save(model, model_path)

    subject_results = {
        "subject_id": subject_id,
        "train_loss": train_loss,
        "test_loss": test_loss,
        "method": METHOD,
        "ROI_num": ROI_NUM,
        "using_steps": USING_STEPS,
        "batch_size": BATCH_SIZE,
        "train_set_proportion": TRAIN_SET_PROPORTION,
        "num_epochs": NUM_EPOCHS,
        "learning_rate": LEARNING_RATE,
        "l2_reg": L2_REG,
    }

    np.save(
        results_path,
        subject_results,
        allow_pickle=True,
    )

    print(f"  Final training loss: {train_loss[-1]:.6f}")
    print(f"  Final test loss    : {test_loss[-1]:.6f}")
    print(f"  Saved model        : {model_path}")
    print(f"  Saved losses       : {results_path}")

    del inputs, targets, model
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return True


# =============================================================================
# Command-line interface
# =============================================================================

def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Train personalized HCP resting-state neural-network models."
        )
    )

    parser.add_argument(
        "--subject",
        type=str,
        default=None,
        help=(
            "Train one participant only. Accepts either the numeric HCP ID "
            "(for example 100206) or the processed-file ID "
            "(for example id_100206)."
        ),
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite models that already exist.",
    )


    return parser.parse_args()


def main() -> None:
    args = parse_arguments()
    save_dir.mkdir(parents=True, exist_ok=True)

    paper_subject_ids = load_paper_subject_ids()

    if args.subject is not None:
        requested_subject = args.subject.strip()

        if not requested_subject.startswith("id_"):
            requested_subject = f"id_{requested_subject}"

        if requested_subject not in paper_subject_ids:
            raise ValueError(
                f"{requested_subject} is not in the paper cohort."
            )

        subject_ids = [requested_subject]
    else:
        subject_ids = paper_subject_ids

    validate_processed_files(subject_ids)

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    print("Repository directory :", repo_dir)
    print("Processed data dir   :", preproc_dir)
    print("Save directory       :", save_dir)
    print("Participants         :", len(subject_ids))
    print("Method               :", METHOD)
    print("Training proportion  :", TRAIN_SET_PROPORTION)
    print("Epochs               :", NUM_EPOCHS)
    print("Batch size           :", BATCH_SIZE)
    print("Learning rate        :", LEARNING_RATE)
    print("L2 regularization    :", L2_REG)
    print("PyTorch version      :", torch.__version__)
    print("CUDA available       :", torch.cuda.is_available())
    print("Running on           :", device)

    if torch.cuda.is_available():
        print("GPU                  :", torch.cuda.get_device_name(0))

    trained_count = 0
    skipped_count = 0

    for subject_id in subject_ids:
        was_trained = train_subject(
            subject_id,
            overwrite=args.overwrite,
        )

        if was_trained:
            trained_count += 1
        else:
            skipped_count += 1

    print("\nTraining complete.")
    print("Models trained :", trained_count)
    print("Models skipped :", skipped_count)


if __name__ == "__main__":
    main()
