#!/usr/bin/env python
# coding: utf-8

"""
Summarize the HCP background-dependence analyses for EC(t) or BEC(t).

Expected input
--------------
The dataframe generated by:

    scripts/04_background_dependence.py

Depending on ``--connectivity-kind``, the script looks for:

    results/HCP_4_df_background_dependence_ECts.pkl
    results/HCP_4_df_background_dependence_BECts.pkl

and falls back to the corresponding CSV file.

Analyses
--------
1. Participant-wise correlation between baseline energy and average
   perturbation magnitude.
2. Participant-wise correlation between baseline energy and average
   evoked energy.
3. Example scatter plots for selected participants.
4. ROI-wise local versus global energy-effect correlations across
   participants.
"""

from pathlib import Path
import argparse

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import pearsonr


# =============================================================================
# Repository paths
# =============================================================================

script_dir = Path(__file__).resolve().parent
hcp_dir = script_dir.parent
repo_dir = hcp_dir.parent.parent
data_dir = hcp_dir / "results" / "dataframes"


# =============================================================================
# Plotting and statistical helpers
# =============================================================================

def nice_axes(ax):
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(ls="--", alpha=0.25)
    return ax


def safe_pearsonr(x, y):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]

    if len(x) < 3:
        return np.nan, np.nan

    if np.allclose(np.std(x), 0) or np.allclose(np.std(y), 0):
        return np.nan, np.nan

    return pearsonr(x, y)


# =============================================================================
# Load background-dependence dataframe
# =============================================================================

def load_background_dependence_dataframe(df_pkl_path, df_csv_path):
    if df_pkl_path.exists():
        df_bd = pd.read_pickle(df_pkl_path)
        print(f"Loaded dataframe from PKL: {df_pkl_path}")
    elif df_csv_path.exists():
        df_bd = pd.read_csv(df_csv_path)
        print(f"Loaded dataframe from CSV: {df_csv_path}")
    else:
        raise FileNotFoundError(
            "Could not find the selected step-4 PKL or CSV file. "
            f"Tried: {df_pkl_path} and {df_csv_path}. "
            "Run scripts/04_background_dependence.py with the same "
            "--connectivity-kind first."
        )

    expected_cols = [
        "sub_id",
        "roi",
        "time",
        "global_baseline_energy",
        "global_evoked_energy",
        "global_effect_size",
        "global_effect_direction",
        "local_baseline_energy",
        "local_evoked_energy",
        "local_effect_size",
        "local_effect_direction",
    ]

    missing_cols = [
        column
        for column in expected_cols
        if column not in df_bd.columns
    ]

    if missing_cols:
        raise ValueError(
            f"Missing expected columns: {missing_cols}"
        )

    df_bd = df_bd.copy()
    df_bd["sub_id"] = df_bd["sub_id"].astype(str)
    df_bd["roi"] = pd.to_numeric(
        df_bd["roi"],
        errors="coerce",
    ).astype(int)
    df_bd["time"] = pd.to_numeric(
        df_bd["time"],
        errors="coerce",
    ).astype(int)

    print("Dataframe shape:", df_bd.shape)
    print(df_bd.head())

    return df_bd


# =============================================================================
# Participant-wise global analyses
# =============================================================================

def compute_subject_global_table(df_bd):
    return (
        df_bd.groupby(
            ["sub_id", "time"],
            as_index=False,
        )
        .agg(
            global_baseline_energy=(
                "global_baseline_energy",
                "first",
            ),
            global_effect_size_mean=(
                "global_effect_size",
                "mean",
            ),
            global_evoked_energy_mean=(
                "global_evoked_energy",
                "mean",
            ),
        )
    )


def compute_global_effect_correlations(subject_global):
    results_global = []
    scatter_data_global = {}

    for sid, sub_df in subject_global.groupby("sub_id"):
        x = sub_df["global_baseline_energy"].to_numpy()
        y = sub_df["global_effect_size_mean"].to_numpy()

        r, p = safe_pearsonr(x, y)

        results_global.append(
            {
                "sub_id": sid,
                "r": r,
                "p": p,
                "n_timepoints": len(sub_df),
            }
        )
        scatter_data_global[sid] = (x, y)

    df_corr_global = (
        pd.DataFrame(results_global)
        .sort_values("sub_id")
        .reset_index(drop=True)
    )

    print(df_corr_global.head())
    print(
        "Average correlation across subjects:",
        df_corr_global["r"].mean(),
    )

    return df_corr_global, scatter_data_global


def plot_global_effect_histogram(df_corr_global):
    plt.figure(figsize=(6.2, 4.0))
    plt.hist(
        df_corr_global["r"].dropna(),
        bins=15,
        edgecolor="k",
        alpha=0.75,
    )
    plt.axvline(
        df_corr_global["r"].mean(),
        linestyle="--",
        linewidth=2,
        label=f"mean r = {df_corr_global['r'].mean():.2f}",
    )
    plt.xlabel(
        "Pearson r (baseline energy vs average effect size)"
    )
    plt.ylabel("Number of subjects")
    plt.title(
        "Distribution of subject-wise energy-effect correlations"
    )
    plt.legend()
    nice_axes(plt.gca())
    plt.tight_layout()
    plt.show()


def plot_selected_subjects(
    scatter_data_global,
    df_corr_global,
):
    n_plot = min(5, len(scatter_data_global))
    sel_subjects = list(scatter_data_global.keys())[:n_plot]

    fig, axs = plt.subplots(
        1,
        n_plot,
        figsize=(4 * n_plot, 4),
        sharey=True,
    )

    if n_plot == 1:
        axs = [axs]

    for ax, sid in zip(axs, sel_subjects):
        x, y = scatter_data_global[sid]
        row = df_corr_global.loc[
            df_corr_global["sub_id"] == sid
        ].iloc[0]

        ax.scatter(
            x,
            y,
            s=12,
            alpha=0.55,
            edgecolors="none",
        )
        ax.set_title(
            f"{sid}\nr={row['r']:.2f}, p={row['p']:.2g}"
        )
        ax.set_xlabel("Baseline energy")

        if ax == axs[0]:
            ax.set_ylabel("Average effect size")

        if np.all(x > 0):
            ax.set_xscale("log")

        nice_axes(ax)

    plt.tight_layout()
    plt.show()


def compute_poststim_correlations(subject_global):
    results_poststim = []
    scatter_data_poststim = {}

    for sid, sub_df in subject_global.groupby("sub_id"):
        x = sub_df["global_baseline_energy"].to_numpy()
        y = sub_df["global_evoked_energy_mean"].to_numpy()

        r, p = safe_pearsonr(x, y)

        results_poststim.append(
            {
                "sub_id": sid,
                "r": r,
                "p": p,
                "n_timepoints": len(sub_df),
            }
        )
        scatter_data_poststim[sid] = (x, y)

    df_corr_poststim = (
        pd.DataFrame(results_poststim)
        .sort_values("sub_id")
        .reset_index(drop=True)
    )

    print(df_corr_poststim.head())
    print(
        "Average correlation across subjects:",
        df_corr_poststim["r"].mean(),
    )

    return df_corr_poststim, scatter_data_poststim


def plot_example_subject_and_roi(df_bd):
    subject_ids = sorted(df_bd["sub_id"].unique())
    sid = subject_ids[0]
    roi = int(
        df_bd.loc[
            df_bd["sub_id"] == sid,
            "roi",
        ].min()
    )

    df_ex = (
        df_bd[
            (df_bd["sub_id"] == sid)
            & (df_bd["roi"] == roi)
        ]
        .sort_values("time")
    )

    x = df_ex["global_baseline_energy"].to_numpy()
    y_effect = df_ex["global_effect_size"].to_numpy()
    y_evoked = df_ex["global_evoked_energy"].to_numpy()

    r1, p1 = safe_pearsonr(x, y_effect)
    r2, p2 = safe_pearsonr(x, y_evoked)

    fig, (ax1, ax2) = plt.subplots(
        1,
        2,
        figsize=(9.0, 3.8),
    )

    ax1.scatter(
        x,
        y_effect,
        s=18,
        alpha=0.6,
        edgecolors="none",
    )
    ax1.set_xlabel("Baseline energy")
    ax1.set_ylabel("Global effect size")
    ax1.set_title(
        f"{sid}, ROI {roi}\n"
        f"Baseline vs effect size\n"
        f"r={r1:.3f}, p={p1:.2g}"
    )

    if np.all(x > 0):
        ax1.set_xscale("log")

    nice_axes(ax1)

    ax2.scatter(
        x,
        y_evoked,
        s=18,
        alpha=0.6,
        edgecolors="none",
    )
    ax2.set_xlabel("Baseline energy")
    ax2.set_ylabel("Global evoked energy")
    ax2.set_title(
        f"{sid}, ROI {roi}\n"
        f"Baseline vs evoked energy\n"
        f"r={r2:.3f}, p={p2:.2g}"
    )

    if np.all(x > 0):
        ax2.set_xscale("log")

    if np.all(y_evoked > 0):
        ax2.set_yscale("log")

    nice_axes(ax2)

    plt.tight_layout()
    plt.show()


# =============================================================================
# ROI-wise local versus global correlations
# =============================================================================

def compute_node_correlations(df_bd):
    subject_ids = sorted(df_bd["sub_id"].unique())
    roi_ids = np.sort(df_bd["roi"].unique())

    rows = []

    for sid in subject_ids:
        sub_df = df_bd[df_bd["sub_id"] == sid]

        for roi in roi_ids:
            node_df = (
                sub_df[sub_df["roi"] == roi]
                .sort_values("time")
            )

            if node_df.empty:
                continue

            r_local, p_local = safe_pearsonr(
                node_df["local_baseline_energy"].to_numpy(),
                node_df["local_effect_size"].to_numpy(),
            )

            r_global, p_global = safe_pearsonr(
                node_df["global_baseline_energy"].to_numpy(),
                node_df["global_effect_size"].to_numpy(),
            )

            rows.append(
                {
                    "sub_id": sid,
                    "roi": int(roi),
                    "r_local": r_local,
                    "p_local": p_local,
                    "r_global": r_global,
                    "p_global": p_global,
                    "n_timepoints": len(node_df),
                }
            )

    df_node_corr = (
        pd.DataFrame(rows)
        .sort_values(["sub_id", "roi"])
        .reset_index(drop=True)
    )

    print(df_node_corr.head())
    print(
        "Node-wise correlation table shape:",
        df_node_corr.shape,
    )

    return df_node_corr


def summarize_and_plot_node_correlations(df_node_corr):
    local_pivot = (
        df_node_corr.pivot(
            index="sub_id",
            columns="roi",
            values="r_local",
        )
        .sort_index(axis=1)
    )

    global_pivot = (
        df_node_corr.pivot(
            index="sub_id",
            columns="roi",
            values="r_global",
        )
        .sort_index(axis=1)
    )

    mean_r_local = local_pivot.mean(axis=0).to_numpy()
    std_r_local = local_pivot.std(
        axis=0,
        ddof=1,
    ).to_numpy()

    mean_r_global = global_pivot.mean(axis=0).to_numpy()
    std_r_global = global_pivot.std(
        axis=0,
        ddof=1,
    ).to_numpy()

    nodes = local_pivot.columns.to_numpy()

    plt.figure(figsize=(9.0, 4.2))

    plt.plot(
        nodes,
        mean_r_local,
        linewidth=2,
        label="Node-wise local mean r",
    )
    plt.fill_between(
        nodes,
        mean_r_local - std_r_local,
        mean_r_local + std_r_local,
        alpha=0.28,
        label="Node-wise local ±1 SD",
    )

    plt.plot(
        nodes,
        mean_r_global,
        linestyle="--",
        linewidth=2,
        label="Node-wise global mean r",
    )
    plt.fill_between(
        nodes,
        mean_r_global - std_r_global,
        mean_r_global + std_r_global,
        alpha=0.18,
        label="Node-wise global ±1 SD",
    )

    plt.xlabel("Brain region (ROI index)")
    plt.ylabel("Correlation (r)")
    plt.title(
        "Energy-effect correlation: "
        "local vs global baseline energy"
    )
    plt.ylim(-1, 1)
    plt.legend()
    nice_axes(plt.gca())
    plt.tight_layout()
    plt.show()

    summary_local_global = (
        pd.DataFrame(
            {
                "roi": local_pivot.columns.to_numpy(),
                "mean_r_local": mean_r_local,
                "std_r_local": std_r_local,
                "mean_r_global": mean_r_global,
                "std_r_global": std_r_global,
            }
        )
        .sort_values("roi")
        .reset_index(drop=True)
    )

    print(summary_local_global.head())

    return summary_local_global


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Summarize the HCP background-dependence dataframe "
            "for EC(t) or BEC(t)."
        )
    )
    parser.add_argument(
        "--connectivity-kind",
        choices=["ECts", "BECts"],
        default="ECts",
        help=(
            "Step-4 dataframe to summarize. The original analysis "
            "was applied separately to ECts and BECts."
        ),
    )
    return parser.parse_args()


def main():
    args = parse_args()
    connectivity_kind = args.connectivity_kind

    df_pkl_path = (
        data_dir
        / f"HCP_4_df_background_dependence_{connectivity_kind}.pkl"
    )
    df_csv_path = (
        data_dir
        / f"HCP_4_df_background_dependence_{connectivity_kind}.csv"
    )

    print("Repository directory :", repo_dir)
    print("Results directory    :", data_dir)
    print("Connectivity kind    :", connectivity_kind)
    print("PKL path             :", df_pkl_path)
    print("CSV path             :", df_csv_path)

    df_bd = load_background_dependence_dataframe(
        df_pkl_path,
        df_csv_path,
    )

    subject_global = compute_subject_global_table(df_bd)

    df_corr_global, scatter_data_global = (
        compute_global_effect_correlations(subject_global)
    )

    plot_global_effect_histogram(df_corr_global)
    plot_selected_subjects(
        scatter_data_global,
        df_corr_global,
    )

    compute_poststim_correlations(subject_global)
    plot_example_subject_and_roi(df_bd)

    df_node_corr = compute_node_correlations(df_bd)
    summarize_and_plot_node_correlations(df_node_corr)


if __name__ == "__main__":
    main()
